src/java/MusicaBean.java
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author mario
 */
@SessionScoped
@ManagedBean
public class MusicaBean implements Serializable {

    private FileUtil fu;
    private List musicas;
    private List pastas;
    private String musicaPlay;
    private String selectedPasta;

    /**
     * @return the fu
     */
    public FileUtil getFu() {
        return fu;
    }

    /**
     * @param fu the fu to set
     */
    public void setFu(FileUtil fu) {
        this.fu = fu;
    }

    @PostConstruct
    public void init() {

        selectedPasta = (selectedPasta == null || selectedPasta.length() < PropertyReader.getProp("rootFolder").length()) 
                ? PropertyReader.getProp("rootFolder") 
                : selectedPasta;

        fu = new FileUtil();
        fu.listFiles(selectedPasta);

        pastas = new ArrayList();
        // Não adiciona a pasta de nível superior caso seja a pasta raiz
        if(!selectedPasta.equals(PropertyReader.getProp("rootFolder"))){
            // Diferentiate windows and Linux slash use
            if(selectedPasta.lastIndexOf("/") > 0){
                pastas.add(selectedPasta.substring(0, selectedPasta.lastIndexOf("/")));
            }
            else{
                pastas.add(selectedPasta.substring(0, selectedPasta.lastIndexOf("\\")));
            }
        }
        pastas.addAll(fu.getFolders());

        if (fu.getFiles().size() > 0) {
            setMusicaPlay(fu.getFiles().get(0));
            musicas = new ArrayList(fu.getFiles());
        } else {
            musicas = new ArrayList();
            setMusicaPlay("");
        }

    }

    public String trocaPasta() {
        init();

        return "index";
    }

    public String troca() {

        if (musicas != null && !musicas.isEmpty()) {
            int index = musicas.indexOf(musicaPlay);
            musicaPlay = (String) musicas.get((index + 1) % musicas.size());
        }
        return "index";
    }

    /**
     * @return the pastas
     */
    public List getPastas() {
        return pastas;
    }

    /**
     * @param pastas the pastas to set
     */
    public void setPastas(List pastas) {
        this.pastas = pastas;
    }

    /**
     * @return the selectedPasta
     */
    public String getSelectedPasta() {
        return selectedPasta;
    }

    /**
     * @param selectedPasta the selectedPasta to set
     */
    public void setSelectedPasta(String selectedPasta) {
        this.selectedPasta = selectedPasta;
    }

    /**
     * @return the musicas
     */
    public List getMusicas() {
        return musicas;
    }

    /**
     * @param musicas the musicas to set
     */
    public void setMusicas(List musicas) {
        this.musicas = musicas;
    }

    /**
     * @return the musicaPlay
     */
    public String getMusicaPlay() {
        return musicaPlay;
    }

    /**
     * @param musicaPlay the musicaPlay to set
     */
    public void setMusicaPlay(String musicaPlay) {
        this.musicaPlay = musicaPlay;
    }

    public String getMusicaPlayName() {
        if (musicaPlay.length() > 0) {
            return musicaPlay.substring(musicaPlay.lastIndexOf("/") + 1);
        } else {
            return "";
        }
    }

    public String getSelectedPastaName() {
        if (selectedPasta.length() > 0) {
            return selectedPasta.substring(selectedPasta.lastIndexOf("/") + 1);
        } else {
            return "";
        }
    }

    public String getMusicaPlayName(String musica) {
        if (musica.length() > 0) {
            return musica.substring(musica.lastIndexOf("/") + 1);
        } else {
            return "";
        }
    }

}

web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>  
<!DOCTYPE html>  
<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:f="http://java.sun.com/jsf/core" >

    <!-- *********************** HEAD *********************** -->
    <h:head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="description" content=""/>
        <meta name="author" content=""/>
        <link rel="shortcut icon" href="./assets/favicon.ico"/>

        <title>CloudSong - #{musicaBean.musicaPlayName}</title>       

        <!-- Bootstrap core CSS -->
        <link href="./css/superhero.css" rel="stylesheet" type="text/css"/>
        <link href="./css/styles.css" rel="stylesheet" type="text/css" />


        <script>
            /**
             * Funão carregar: abre o modal com as músicas na tela
             * apenas se houver músicas carregadas
             * @returns {undefined}
             */
            function carregar() {
                if (#{musicaBean.musicas.size() > 0}) {
                    $('#myModal').modal('show');
                }
            }
        </script>
    </h:head>

    <!-- *********************** BODY *********************** -->
    <h:body id="thisBody" onload="carregar()">        

        <h:form id="menu">
            <div class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand Lobster" href="index.xhtml"><label class="glyphicon glyphicon-volume-up text-warning"/>  CloudSong</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">

                            <!-- Menu Registros >
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Registros <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><h:commandLink action="#{registrosBean.novo}" value="Novo Registro"/></li>
                                    <li><a href="ata.jsf">Ata de Reunião</a></li>
                                    <li class="divider"></li>
                                    <li><a href="registros.jsf">Visualizar Registros</a></li>
                                </ul>
                            </li-->                           
                        </ul>
                    </div>
                </div>
            </div>
        </h:form>


        <div class="container">

            <h:form class="jumbotron" p:role="form" id="mainForm">


                <div class="row">
                    <div class="col-md-12">
                        <h4>
                            <h:outputLabel class="text-warning" value="# #{musicaBean.selectedPastaName}" />

                            <h:outputLink class="btn btn-warning btn-sm pull-right" id="botaoModal" value="#myModal" p:data-toggle="modal">
                                Abrir Player
                            </h:outputLink>
                        </h4>
                    </div>
                </div>


                <br/>


                <div class="row">
                    <div class="col-md-12">
                        <h:dataTable class="table table-striped table-hover table-responsive"  value="#{musicaBean.pastas}" var="item" border="1">
                            <h:column>
                                <f:facet name="header">
                                    Pastas
                                </f:facet>

                                <h:commandLink title="#{item}" value="#{item}" action="#{musicaBean.trocaPasta}">
                                    <f:setPropertyActionListener target="#{musicaBean.selectedPasta}"  value="#{item}"/>
                                </h:commandLink>                                
                            </h:column>                         
                        </h:dataTable>                        

                    </div>
                </div>
            </h:form>

            <h:form id="modalForm">
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">

                            <!-- Cabeçalho Modal -->
                            <div class="modal-header">
                                <a class="close text-warning" data-dismiss="modal">×</a>
                                <h4 class="modal-title text-warning" id="myModalLabel">#{musicaBean.selectedPastaName}  [#{musicaBean.musicaPlayName}]</h4>
                            </div>

                            <!-- Corpo Modal -->
                            <div class="modal-body">

                                <audio id="player" class="table" controls="true" src="#{musicaBean.musicaPlay}" 
                                       onended="history.go(0);#{musicaBean.troca()}" preload="auto" autoplay="autoplay">
                                    Your browser does not support the audio element.
                                </audio>

                                <h:dataTable class="table table-condensed table-responsive table-bordered table-hover table-striped"  
                                             value="#{musicaBean.musicas}" var="item" border="1">
                                    <h:column >
                                        <h:commandLink value="#{musicaBean.getMusicaPlayName(item)}">                                        
                                            <f:setPropertyActionListener target="#{musicaBean.musicaPlay}"  value="#{item}"/>
                                        </h:commandLink>                                
                                    </h:column>                         
                                </h:dataTable>                                
                            </div>
                            <!-- Rodapé Modal -->
                            <div class="modal-footer">
                                <button type="button" class="btn btn-sm btn-warning" data-dismiss="modal">Fechar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </h:form>
        </div>

        <h:form id="footer">
            <div id="footerNavbar" class="navbar navbar-fixed-bottom" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <h:outputLabel class="text-center text-muted" value="Mário Henrique Gontijo Freitas - 2014"/>
                    </div>
                </div>
            </div>
        </h:form>        

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->       
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="./js/bootstrap.min.js"></script>        
    </h:body>
</html>